<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TeamSaam" failures="3" tests="42" name="com.testng.AnnotationsEx" time="0.165" errors="0" timestamp="2022-12-22T01:22:55 EST" skipped="3">
  <testcase classname="com.testng.AnnotationsEx" name="atest4" time="0.030">
    <failure message="Testcase is Passed expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Testcase is Passed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at com.testng.AnnotationsEx.atest4(AnnotationsEx.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- atest4 -->
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="atest4" time="0.031">
    <failure message="Testcase is Passed expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Testcase is Passed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at com.testng.AnnotationsEx.atest4(AnnotationsEx.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- atest4 -->
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="atest4" time="0.032">
    <failure message="Testcase is Passed expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Testcase is Passed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at com.testng.AnnotationsEx.atest4(AnnotationsEx.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- atest4 -->
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="atest5" time="0.000">
    <skipped/>
  </testcase> <!-- atest5 -->
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="atest5" time="0.000">
    <skipped/>
  </testcase> <!-- atest5 -->
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="atest5" time="0.001">
    <skipped/>
  </testcase> <!-- atest5 -->
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="ctest2" time="0.003"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="ctest2" time="0.002"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="ctest2" time="0.001"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.002"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.002"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.001"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.001"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.001"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.002"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.000"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.008"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.000"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.002"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.001"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.007"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.000"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.003"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.015"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.000"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.003"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.000"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.002"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.004"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.000"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.000"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.000"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.002"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.000"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.000"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.000"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.001"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.000"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="dtest1" time="0.002"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="btest3" time="0.000"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="btest3" time="0.000"/>
  <system-out/>
  <testcase classname="com.testng.AnnotationsEx" name="btest3" time="0.006"/>
  <system-out/>
</testsuite> <!-- com.testng.AnnotationsEx -->
